version: "2"
services:
    #
    # SSL certification service
    #  Requests certs from Letsencrypt service, if they are not available then it falls back to
    #  self generated certificates
    #
    gateway_letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
        restart: always
        volumes_from:
            - gateway
            - gateway_proxy_gen
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - NGINX_DOCKER_GEN_CONTAINER=${COMPOSE_PROJECT_NAME}_gateway_proxy_gen_1
            - NGINX_PROXY_CONTAINER=${COMPOSE_PROJECT_NAME}_gateway_1

            # @debugging: Enable to test if the Letsencrypt is properly configured
            #- ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
        labels:
            com.centurylinklabs.watchtower.enable: true
